# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facial_Vectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vector', models.TextField(null=True)),
                ('matrix', models.TextField(null=True)),
                ('mean', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hillary_trump.Facial_Vectors')),
            ],
        ),
    ]
