# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hillary_trump', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'/image_upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
