# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hillary_trump', '0002_auto_20161106_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageattachment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=b'/image_upload/'),
        ),
    ]
