# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hillary_trump', '0003_auto_20161106_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='path',
            field=models.CharField(max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=b'/home/sravanth/Desktop/face_recognition/image_upload'),
        ),
    ]
