# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hillary_trump', '0004_auto_20161106_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='name',
            field=models.CharField(max_length=200000, null=True),
        ),
    ]
